### ISSUE TITLE
Flaky Test Tracking

### ISSUE THREAD

**Issue by nicholas-codecov** [codecov/gazebo#2419]
The following are current tests that are flaky and need to be fixed:

- [x] `src/pages/PullRequestPage/subroute/FileExplorer/hooks/useRepoPullContentsTable.spec.js`
- [x] `src/pages/RepoPage/CoverageTab/CoverageTab.spec.jsx`
- [x] `src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.spec.jsx`
- [x] `src/pages/AccountSettings/tabs/Admin/ManageAdminCard/AdminTable/AdminTable.spec.jsx`
- [x] `src/pages/PullRequestPage/subroute/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.spec.js`
- [x] `src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/CommitDetailFileExplorer.spec.jsx`

**Comment by RulaKhaled** [comment]
> The following are current tests that are flaky and need to be fixed:
> 
> * [ ]  `src/pages/PullRequestPage/subroute/FileExplorer/hooks/useRepoPullContentsTable.spec.js`
> * [ ]  `src/pages/RepoPage/CoverageTab/CoverageTab.spec.jsx`
> * [ ]  `src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.spec.jsx`
> * [ ]  `src/pages/AccountSettings/tabs/Admin/ManageAdminCard/AdminTable/AdminTable.spec.jsx`
> * [ ]  `src/pages/PullRequestPage/subroute/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.spec.js`
> * [ ]  `src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/CommitDetailFileExplorer.spec.jsx`

Skipping test in `src/pages/PullRequestPage/subroute/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.spec.js` until the flakiness is resolved. PR https://github.com/codecov/gazebo/pull/2425/
